---
title: "Linear Algera for Data Science in R"
author: "Ken Harmon"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:  
    keep_md: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
editor_options: 
  chunk_output_type: console
---

# {.tabset .tabset-fade}

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(ggfortify)
theme_set(theme_bw())
```

https://www.datacamp.com/courses/linear-algebra-for-data-science-in-r

## Intro to Linear Algebra

https://campus.datacamp.com/courses/linear-algebra-for-data-science-in-r/introduction-to-linear-algebra?ex=1

### Motivations
```{r motivations}
x <- rep(1, 4)
y <- seq(2, 8, by = 2)
z <- c(1, 5, -2, 4)
z[3] <- 7

matrix(2, 3, 2)
matrix(c(1, -1, 2, 3, 2, -2), nrow = 2, ncol = 3, byrow = TRUE)
matrix(c(1, -1, 2, 3, 2, -2), nrow = 2, ncol = 3, byrow = FALSE)
```
### Creating Vecors in R

```{r cvir}
# Creating three 3's and four 4's, respectively
rep(3, 3)
rep(4, 4)

# Creating a vector with the first three even numbers and the first three odd numbers
seq(2, 6, by = 2)
seq(1, 5, by = 2)

# Re-creating the previous four vectors using the 'c' command
c(3, 3, 3)
c(4, 4, 4, 4)

c(2, 4, 6)
c(1, 3, 5)
```
### The Algebra of Vectors

```{r aov}
x <- seq(1,7,by=1)
y <- seq(2,14, by=2)
z <- c(1,1,2)

# Add x to y and print
print(x + y)

# Multiply z by 2 and print
print(2 * z)

# Multiply x and y by each other and print
print(x * y)

# Add x to z, if possible, and print
print(x + z)
```

## Creating Matrices in R

```{r CMiR}
# Create a matrix of all 1's and all 2's that are 2 by 3 and 3 by 2, respectively
matrix(1, nrow = 2, ncol = 3)

print(matrix(2, nrow = 3, ncol = 2))

# Create a matrix B and changing the byrow designation.
B <- matrix(c(1, 2, 3, 2), nrow = 2, ncol = 2, byrow = FALSE)
B <- matrix(c(1, 2, 3, 2), nrow = 2, ncol = 2, byrow = TRUE)

# Add A to the previously-created matrix B
A <- matrix(1, nrow = 2, ncol = 2)
A + B
```
## Matrix-Vector Operations

```{r MVO}
A <- matrix(c(4,0,0,1), nrow = 2, ncol = 2, byrow = T)
b <- c(1,1)
B <- matrix(c(1,0,0,2/3), nrow = 2, ncol = 2, byrow = T)

# Multiply A by b
A %*% b

# Multiply B by b
B %*% b

A <- matrix(c(-1,0,0,1), nrow = 2, ncol = 2, byrow = T)
b <- c(2,1)
B <- matrix(c(1,0,0,-1), nrow = 2, ncol = 2, byrow = T)
C <- matrix(c(-4,0,0,-2), nrow = 2, ncol = 2, byrow = T)

# Multiply A by b
A%*%b

# Multiply B by b 
B%*%b

# Multiply C by b 
C%*%b
```

### Matrix-Matrix Calulations

```{r MMC}
c <- sqrt(2)/2
A <- matrix(c(c,c,-c,c), nrow=2, ncol = 2, byrow = F) #rotation of a 2-dimensional vector by 45 degrees counterclockwise
b <- c(1,1)

# Multiply A by B
A%*%B

# Multiply A on the right of B
B%*%A

# Multiply the product of A and B by the vector b
A%*%B%*%b

# Multiply A on the right of B, and then by the vector b
B%*%A%*%b
```

```{r Inv}
A <- matrix(c(1,2,-1,2), nrow = 2, ncol = 2, byrow = T)

# Take the inverse of the 2 by 2 identity matrix
solve(diag(2))

# Take the inverse of the matrix A
Ainv <- solve(A)

# Multiply A inverse by A
Ainv%*%A

# Multiply A by its inverse
A%*%Ainv
```


## Matrix-Vector Equations

```{r MVE}
wnba <- read.csv("wnba.csv")
M <- data.frame(wnba)
rownames(M) <- as.character((M[,1]))
M <- M[,-1]

# Print the Massey Matrix M

print(M)

wnbapd <- read.csv("wnbapd.csv")
fdf <- data.frame(wnbapd)
f <- data.frame(fdf[,2])
rownames(f) <- as.character((fdf[,1]))
colnames(f) <- c("Differential")

# Print the vector of point differentials f 
print(f)

# Find the sum of the first column of M
sum(M[1])

# Find the sum of the vector f
sum(f)

```

```{r AMM}
# Add a row of 1's
M_2 <- rbind(M, 1)

# Add a column of -1's 
M_3 <- cbind(M_2, rep(-1, 13))

# Change the element in the lower-right corner of the matrix
M_3[13, 13] <- 1

# Print M_3
print(M_3)

M_3 <- cbind(M, -1)
M_2 <- rbind(M_3, 1)
M<-M_2
```

```{r IMM}
solve(M)
```

```{r 2017Wr}
f <- rbind(f,0)
f <- as.matrix(f)
M <- as.matrix(M)
# Solve for r and rename column
r <- solve(M)%*%f
colnames(r) <- "Rating"

# Print r
print(r)

R<-data.frame(r)
R<-cbind(rownames(R),R)
R<-R[1:12,]
arrange(R, -Rating)
```

```{r AttRMI}
# Print M
print(M)

# Find the rating vector the conventional way
r <- solve(M)%*%f
colnames(r) <- "Rating"
print(r)

# Find the rating vector using ginv
r <- ginv(M)%*%f
colnames(r) <- "Rating"
print(r)
```

## Eigenvalues and Eigenvectors

```{r SDA}
A<-matrix(c(2,0,0,2/3),nrow=2,ncol=2,byrow=F)
# Multiply A by the given vector
print(A%*%c(1,1))
```

```{r FE}
A<-matrix(c(-1,0,0,2,7,0,4,12,-4),nrow=3,ncol=3,byrow=F)

# Show that 7 is an eigenvalue for A
A%*%c(0.2425356, 0.9701425, 0) - 7*c(0.2425356, 0.9701425, 0)

# Show that -4 is an eigenvalue for A
A%*%c(-0.3789810, -0.6821657, 0.6253186) - (-4)*c(-0.3789810, -0.6821657, 0.6253186)

# Show that -1 is an eigenvalue for A
A%*%c(1,0,0) - (-1)*c(1,0,0)
```

```{r SMEE}
# Show that double an eigenvector is still an eigenvector
A%*%((2)*c(0.2425356, 0.9701425, 0)) - 7*(2)*c(0.2425356, 0.9701425, 0)

# Show half of an eigenvector is still an eigenvector
A%*%((0.5)*c(0.2425356, 0.9701425, 0)) - 7*(0.5)*c(0.2425356, 0.9701425, 0)
```

```{r VME}
A<-matrix(c(1,1,2,1),nrow=2,ncol=2,byrow=F)

# Compute the eigenvalues of A and store in Lambda
Lambda <- eigen(A)

# Print eigenvalues
print(Lambda$values[1])
print(Lambda$values[2])

# Verify that these numbers satisfy the conditions of being an eigenvalue
det(Lambda$values[1]*diag(2) - A)
det(Lambda$values[2]*diag(2) - A)
```

```{r CEV}
# Find the eigenvectors of A and store them in Lambda
Lambda <- eigen(A)

# Print eigenvectors
print(Lambda$vector[, 1])
print(Lambda$vectors[, 2])

# Verify that these eigenvectors & their associated eigenvalues satisfy Av - lambda v = 0
Lambda$values[1]*Lambda$vectors[, 1] - A%*%Lambda$vectors[, 1]
Lambda$values[2]*Lambda$vectors[, 2] - A%*%Lambda$vectors[, 2]
```

```{r MMAF}
M <- data.matrix(M)

# This code iterates mutation 1000 times
x <- c(1, 0, 0, 0)
for (j in 1:1000) {x <- M%*%x}

# Print x
print(x)

# Print and scale the first eigenvector of M
Lambda <- eigen(M)
v1 <- Lambda$vectors[, 1]/sum(Lambda$vector[, 1])

# Print v1
print(v1)
```

## Priciple Component Analysis

```{r FR}
combine <- read.csv("combine.csv")
combine <- combine[,2:14]

# Print the first 6 observations of the dataset
head(combine)

# Find the correlation between variables forty and three_cone
cor(combine$forty, combine$three_cone)
plot(combine$forty, combine$three_cone)

# Find the correlation between variables vertical and broad_jump
cor(combine$vertical,combine$broad_jump)
plot(combine$vertical,combine$broad_jump)
```

```{r SYD}
# Extract columns 5-12 of combine
A <- combine[, 5:12]

# Make A into a matrix
A <- as.matrix(A)

# Subtract the mean of each column
A[, 1] <- A[, 1] - mean(A[, 1])
A[, 2] <- A[, 2] - mean(A[, 2])
A[, 3] <- A[, 3] - mean(A[, 3])
A[, 4] <- A[, 4] - mean(A[, 4])
A[, 5] <- A[, 5] - mean(A[, 5])
A[, 6] <- A[, 6] - mean(A[, 6])
A[, 7] <- A[, 7] - mean(A[, 7])
A[, 8] <- A[, 8] - mean(A[, 8])
```

```{r VCC}
# Create matrix B from equation in instructions
B <- t(A)%*%A/(nrow(A) - 1)

# Compare 1st element of the 1st column of B to the variance of the first column of A
B[1,1]
var(A[, 1])

# Compare 1st element of 2nd column of B to the 1st element of the 2nd row of B to the covariance between the first two columns of A
B[1, 2]
B[2, 1]
cov(A[, 1], A[, 2])
```

```{r EA}
# Find eigenvalues of B
V <- eigen(B)

# Print eigenvalues
print(V$values)
```

```{r PCA}
prcomp(A)
# the weights of each variable in each priciple component
summary(prcomp(A))
# look at the proportion of the variance
head(prcomp(A)$x)
# each player's contribution to each priciple component
head(cbind(combine[, 1:4], prcomp(A)$x[, 1:2]))
```

```{r SDBPCA}
# Scale columns 5-12 of combine
B <- scale(combine[, 5:12])
C <- combine[,5:12]

# Print the first 6 rows of the data
head(B)

# Summarize the principal component analysis
summary(prcomp(B))
summary(prcomp(C))
back <- cbind(combine[, 1:4], prcomp(B)$x[, 1:2])

head(back)

autoplot(prcomp(B), data=back, colour = "position" )
```

```{r SPCAr}
# Subset combine only to "WR"
combine_WR <- subset(combine, position == "WR")

# Scale columns 5-12 of combine_WR
B <- scale(combine_WR[, 5:12])

# Print the first 6 rows of the data
head(B)

# Summarize the principal component analysis
summary(prcomp(B))
```

